### ISSUE TITLE
Template interceptor doesn't substitute numbers as expected

### ISSUE THREAD

**Issue by optical** [cujojs/rest#110] opened 2015-04-12 10:12 UTC
The template interceptor silently ignores any parameters where the value is a number. This seems somewhat tricky and tripped me up when trying to format a URI such as `/{year}/{month}/{day}` with a params object of `{ year: 2015, month: 04, day: 12}`

If there is a reason it doesn't handle format strings I think it should be added to the docs. Otherwise, perhaps it should check for both strings, numbers and potentially booleans? The offending code is in `util/uriTemplate.js`

What do you reckon?

**Comment by scothis** [comment] 2015-04-12 16:32
@optical this is a duplicate of #108. The short answer is that numbers are not explicitly supported by the URI Template spec, so I missed the use case. There is a fix on the dev branch which I'll release in the next couple days.

**Closed by scothis** 2015-04-12 16:32 UTC
